spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bassurance
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    flyway:
      baseline-on-migrate: true
      enabled: true
      user: postgres
      password: 123456789
      baseline-description: "init"
      baseline-version: 0

SERVER:
  PORT: 8081