CREATE TABLE partners (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    address VARCHAR(255) NOT NULL,
    rep_name VARCHAR(255) NOT NULL,
    rep_phone VARCHAR(20) NOT NULL,
    rep_email VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL
);
